[package]
name = "bevy-vsrg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.8.1", features=["wav"]}
bevy_prototype_lyon = "0.6.0"
chrono = "0.4.22"
rand = "0.8.5"
